import React, { useState } from 'react';

function flattenTopics(topics, depth = 0) {
  const result = [];
  topics?.forEach((t) => {
    result.push({ ...t, depth });
    if (t.subtopics?.length) {
      result.push(...flattenTopics(t.subtopics, depth + 1));
    }
  });
  return result;
}

export default function ExportPDFButton({ subject, progress, pct }) {
  const [loading, setLoading] = useState(false);

  const handleExport = async () => {
    setLoading(true);
    try {
      const html2pdf = (await import('html2pdf.js')).default;

      const flat = flattenTopics(subject?.syllabus || []);
      const topicsHTML = flat
        .map((t) => {
          const indent = t.depth * 20;
          const statusEmoji =
            t.status === 'done' ? '✅' : t.status === 'in-progress' ? '🔄' : '⬜';
          const strike = t.status === 'done' ? 'text-decoration:line-through;color:#94a3b8;' : '';
          return `<tr style="border-bottom:1px solid #e2e8f0;">
            <td style="padding:8px 4px;padding-left:${indent + 8}px;font-size:13px;${strike}">${statusEmoji} ${t.title}</td>
            <td style="padding:8px;text-align:center;font-size:13px;">${
              t.status === 'done' ? 'Done' : t.status === 'in-progress' ? 'In Progress' : 'Not Started'
            }</td>
          </tr>`;
        })
        .join('');

      const html = `
        <div style="font-family:Inter,Arial,sans-serif;max-width:700px;margin:0 auto;padding:32px;color:#1e293b;">
          <div style="border-bottom:3px solid #0ea5e9;padding-bottom:16px;margin-bottom:24px;">
            <h1 style="font-size:28px;font-weight:900;color:#0f172a;margin:0;">${subject?.name}</h1>
            <p style="color:#64748b;margin:4px 0 0;">Exported from SyllabiQ · ${new Date().toLocaleDateString()}</p>
            ${subject?.description ? `<p style="color:#475569;margin:8px 0 0;">${subject.description}</p>` : ''}
          </div>

          <div style="display:flex;gap:24px;margin-bottom:24px;">
            <div style="flex:1;background:#f0f9ff;border-radius:12px;padding:16px;text-align:center;">
              <div style="font-size:36px;font-weight:900;color:#0ea5e9;">${pct}%</div>
              <div style="font-size:13px;color:#64748b;">Overall Progress</div>
            </div>
            <div style="flex:1;background:#f0fdf4;border-radius:12px;padding:16px;text-align:center;">
              <div style="font-size:36px;font-weight:900;color:#10b981;">${flat.filter((t) => t.status === 'done').length}</div>
              <div style="font-size:13px;color:#64748b;">Topics Done</div>
            </div>
            <div style="flex:1;background:#fafafa;border-radius:12px;padding:16px;text-align:center;">
              <div style="font-size:36px;font-weight:900;color:#64748b;">${flat.length}</div>
              <div style="font-size:13px;color:#64748b;">Total Topics</div>
            </div>
          </div>

          <h2 style="font-size:16px;font-weight:700;margin-bottom:12px;color:#0f172a;">Syllabus Topics</h2>
          <table style="width:100%;border-collapse:collapse;font-size:13px;">
            <thead>
              <tr style="background:#f1f5f9;">
                <th style="padding:10px 8px;text-align:left;font-weight:700;color:#475569;">Topic</th>
                <th style="padding:10px 8px;text-align:center;font-weight:700;color:#475569;width:120px;">Status</th>
              </tr>
            </thead>
            <tbody>${topicsHTML}</tbody>
          </table>

          <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:12px;color:#94a3b8;text-align:center;">
            Generated by SyllabiQ · Collaborative Syllabus Tracker
          </div>
        </div>
      `;

      const element = document.createElement('div');
      element.innerHTML = html;
      document.body.appendChild(element);

      await html2pdf()
        .set({
          margin: 10,
          filename: `${subject?.name?.replace(/\s+/g, '_') || 'subject'}_progress.pdf`,
          html2canvas: { scale: 2, useCORS: true },
          jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        })
        .from(element)
        .save();

      document.body.removeChild(element);
    } catch (err) {
      console.error('PDF export error:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <button className="btn-secondary" onClick={handleExport} disabled={loading}>
      {loading ? (
        <span className="flex items-center gap-2">
          <div className="w-3 h-3 border-2 border-slate-400 border-t-transparent rounded-full animate-spin" />
          Exporting...
        </span>
      ) : (
        <>📄 Export PDF</>
      )}
    </button>
  );
}
